<head>
    <title>flowppy</title>
    <link rel="stylesheet" media="screen" type="text/css" href="assets/css/bootstrap.css"/>
    <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <link rel="shortcut icon" type="image/x-icon" href="assets/images/icone.ico" />
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
                <a class="navbar-brand" href="index">flowppy </a>
            </div>
            <div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="./createur_graphe">Créer son graphe !</a>
                    </li>
                    <li>
                        <a href="https://github.com/natinusala/flowppy/wiki"> Documentation </a>
                    </li>
                    <li>
                        <a href="https://github.com/natinusala/flowppy/"> Suivez nous sur <img style="height: 21px;" src="http://www.gallery.art404.com/images/github.svg"></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <?php echo $contentForLayout; ?>
</body>